hyperion:
  imageRepository: ghcr.io/DiamondLightSource
  # i03-hyperion user and group
  runAsUser: 36101
  runAsGroup: 36101
  supplementalGroups: []
  beamline: i03
  dev: false
  logDir: "/dls_sw/i03/logs/bluesky"
  # These should be overridden at install time
  projectDir: SET_ON_INSTALL
  appVersion: SET_ON_INSTALL
dodal:
  projectDir: SET_ON_INSTALL
service:
  type: NodePort
