# Changes here will be overwritten by Copier
_commit: 4.2.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: dominic.oram@diamond.ac.uk
author_name: Dominic Oram
component_lifecycle: production
component_owner: group:data-acquisition
component_type: library
description: Bluesky tools for MX Beamlines at DLS
distribution_name: mx-bluesky
docker: false
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: mx_bluesky
pypi: true
repo_name: mx-bluesky
strict_typing: false
type_checker: pyright
