# Changes here will be overwritten by Copier
_commit: 2.2.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: dominic.oram@diamond.ac.uk
author_name: Dominic Oram
component_owner: MX DAQ
description: Bluesky tools for MX Beamlines at DLS
distribution_name: mx_bluesky
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: mx_bluesky
pypi: true
repo_name: mx_bluesky
type_checker: pyright
