apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mx_bluesky
  title: mx_bluesky
  description: Bluesky tools for MX Beamlines at DLS
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: DiamondLightSource/mx_bluesky
  tags:
    - python
    - bluesky
spec:
  type: library
  lifecycle: production
  owner: group:data-acquisition
