comment:
  layout: "header, diff, flags, components" # show component info in the PR comment

component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project
        target: 85%
        threshold: 1%
  individual_components:
    - component_id: module_i24_ssx
      name: i24 SSX
      paths:
        - beamlines/i24/serial/**
      statuses:
        - type: project
          target: 60%
          threshold: 1%

ignore:
  - "**/conftest.py"
