# Before changing this BlueAPI version number, you should check that 
# the BlueAPI pin in pyproject.toml is compatible, else the version will
# be overridden
FROM ghcr.io/diamondlightsource/blueapi:latest
USER root

ARG DEBIAN_FRONTEND=noninteractive

# Need:
# libgl, libglib2.0 for python cv2 dependency 
RUN apt update -y && \
    apt upgrade -y && \
    apt install -y libgl1 libglib2.0-0

RUN uv pip install --no-cache-dir --no-compile mx-bluesky

RUN chmod -R 777 /root/.cache/

USER ubuntu
