application:
  imageRepository: ghcr.io/diamondlightsource
  imageName: hyperion
  imageVersion: SET_ON_INSTALL
  beamline: i03
  dev: false
  logDir: "/var/logs/mx-bluesky"
  terminationGracePeriodSeconds: 30
  env:
    EPICS_CA_NAME_SERVERS: "gateways:9064"
    EPICS_PVA_NAME_SERVERS: "gateways:9065"
supervisor:
  servicePort: 80
  containerPort: 5006
  runAsUser: 1000
  runAsGroup: 1000
callbacks:
  runAsUser: 1000
  runAsGroup: 1000
initContainer:
  dodalBranch: "main"
scratch:
  volumeSize: "2Gi"
configServer:
  url: http://i03-daq-config-server.diamond.ac.uk
graylog:
  url: "tcp://graylog-log-target.diamond.ac.uk:12232"
stomp:
  url: tcp://localhost:61613
blueapi:
  url: http://my.blueapi.service:5005
volumes:
  logging:
    - name: logdir
      emptyDir: {}
# In ixx-services, replace with path to relevant log folder, e.g.
#      hostPath:
#        path: "/dls_sw/i03/logs/bluesky/hyperion-k8s"
#        type: Directory
  data:
    - name: data
      emptyDir: {}
# In ixx-services, replace with path to relevant data folder, e.g.
#      hostPath:
#        type: Directory
#        path: "/dls/i03/data"
zocalo:
  defaultTransport: "PikaTransport"
  graylog:
    host: graylog-log-target.diamond.ac.uk
    port: 12208
    protocol: UDP
  secrets:
    - name: rabbitmq
      secretName: rmq-creds
      fileName: rabbitmq-credentials.yml
