@startuml
title Gridscan Parameter Relationships

package dodal {
    class AbstractExperimentParameterBase
    class AbstractExperimentWithBeamParams {
        transmission_fraction
    }
    class GridScanParamsCommon {
        x_steps
        y_steps
        x_step_size_mm
        y_step_size_mm
        x_start_mm
        y1_start_mm
        z1_start_mm
        set_stub_offsets
    }
    class GridScanParamsThreeD
    class PandAGridScanParams
    class ZebraGridScanParamsThreeD
    class ZebraGridScanParamsTwoD
}

rectangle "Internal Experiment Parameter Model" {
    class MxBlueSkyParameters
    class DiffractionExperiment
    class DiffractionExperimentWithSample
    class GenericGrid {
        grid_width_um
        exposure_time_s
    }
    class GenericGridWithHyperionDetectorParams
    class GridScanWithEdgeDetect {
        box_size_um
    }
    class PinTipCentreThenXrayCentre
    class RobotLoadThenCentre
}



rectangle "Specified Grids" {
    class SpecifiedGrids<GenericParamType> {
        omega_starts_deg: float[]
        x_step_size_um
        y_step_sizes_um
        x_steps
        y_steps: int[]
        --
        fast_grid_scan_params: GenericParamType
        grid_specs
        scan_indices
        scan_points
        scan_spec
        num_images
    }
    class "SpecifiedGrids<ZebraGridScanParamsThreeD>" as SpecifiedGridsZebraGridScanParamsThreeD
    class "SpecifiedGrids<ZebraGridScanParamsTwoD>" as SpecifiedGridsZebraGridScanParamsTwoD
    class SpecifiedTwoDGridScan
    class SpecifiedThreeDGridScan
    class HyperionSpecifiedThreeDGridScan {
        --
        panda_fast_gridscan_params: PandAGridScanParams
    }
}

class XyzStarts {
    x_start_um
    y_start_um
    z_start_um
}
class OptionalXYZStarts {
    x_start_um
    y_start_um
    z_start_um
}

MxBlueSkyParameters <|-- DiffractionExperiment
DiffractionExperiment <|-- DiffractionExperimentWithSample
DiffractionExperimentWithSample <|-- GenericGrid
GenericGrid <|-- GenericGridWithHyperionDetectorParams
GenericGridWithHyperionDetectorParams <|-- GridScanWithEdgeDetect
GenericGridWithHyperionDetectorParams <|-- PinTipCentreThenXrayCentre
GenericGridWithHyperionDetectorParams <|-- RobotLoadThenCentre
GenericGrid <|-- SpecifiedGrids
SpecifiedGridsZebraGridScanParamsTwoD <|-- SpecifiedTwoDGridScan
SpecifiedGridsZebraGridScanParamsThreeD <|-- SpecifiedThreeDGridScan
SpecifiedThreeDGridScan <|-- HyperionSpecifiedThreeDGridScan
XyzStarts <|-- SpecifiedGrids
OptionalXYZStarts <|-- RotationScanPerSweep
class GridParamUpdate {
    x_start_um: float
    y_starts_um: float[]
    z_starts_um: float[]
    x_steps: float
    y_steps: float[]
    x_step_size_um: float
    y_step_sizes_um: float[]
}

class GridDetectionCallback {
    get_grid_parameters() -> GridParamUpdate
}
    
GridDetectionCallback --> GridParamUpdate : generates from event. Adds 0.5 to get box-centres
GridParamUpdate --> HyperionSpecifiedThreeDGridScan : combines with GridScanWithEdgeDetect

class experiment_plans {
    grid_detect_then_xray_centre()
    common_flyscan_xray_centre()
    create_parameters_for_flyscan_xray_centre(GridScanWithEdgeDetect, GridParamUpdate) -> HyperionSpecifiedThreeDGridScan
}

AbstractExperimentParameterBase <|-- AbstractExperimentWithBeamParams
AbstractExperimentWithBeamParams <|-- GridScanParamsCommon
GridScanParamsCommon <|-- ZebraGridScanParamsTwoD
GridScanParamsCommon <|-- GridScanParamsThreeD
GridScanParamsThreeD <|-- PandAGridScanParams
GridScanParamsThreeD <|-- ZebraGridScanParamsThreeD

HyperionSpecifiedThreeDGridScan --> ZebraGridScanParamsThreeD : generates
HyperionSpecifiedThreeDGridScan --> PandAGridScanParams : generates
SpecifiedTwoDGridScan --> ZebraGridScanParamsTwoD : generates
@enduml
