def test_xbpm_preprocessor_does_nothing_on_non_specified_message(): ...


def test_xbpm_preprocessor_runs_inserts_correct_plan_on_correct_message(): ...


def test_xbpm_preprocessor_runs_appends_correct_plan_on_correct_message(): ...


def test_xbpm_preprocessor_unpauses_xbpm_on_exception(): ...
