apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperion-deployment
spec:
  selector:
    matchLabels:
      app: hyperion
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: hyperion
    spec:
      volumes:
        - name: scratch
          persistentVolumeClaim:
            claimName: hyperion-supervisor-scratch-{{ .Values.application.imageVersion }}
        - name: supervisor-config
          configMap:
            name: hyperion-supervisor-config
        - name: callbacks-config
          configMap:
            name: hyperion-callbacks-config
        {{- toYaml .Values.volumes.logging | nindent 8 }}
        {{- toYaml .Values.volumes.data | nindent 8 }}
        - name: expeye-secrets
          secret:
            secretName: ispyb-hyperion-cfg
        - name: zocalo-config
          configMap:
            name: zocalo-config
            defaultMode: 420
        - name: zocalo-secrets
          secret:
            secretName: rmq-creds
        - name: etc
          configMap:
            name: hyperion-etc-config
            defaultMode: 420
        # Required for vscode to install remote debugging plugins in the debug container
        - name: debug-home
          emptyDir:
            sizeLimit: 1Gi
      initContainers:
        - name: hyperion-init
          image: {{ .Values.application.imageRepository}}/hyperion:{{ .Values.application.imageVersion }}
          command: ['/app/scripts/initialise_scratch.sh']
          volumeMounts:
            - name: scratch
              mountPath: "/scratch"
            - name: etc
              mountPath: /etc/passwd
              subPath: passwd
            - name: etc
              mountPath: /etc/group
              subPath: group
          env:
            - name: HOME
              value: /tmp
            - name: DODAL_BRANCH
              value: {{ .Values.initContainer.dodalBranch }}
          securityContext:
            runAsGroup: {{ .Values.supervisor.runAsGroup }}
            runAsUser: {{ .Values.supervisor.runAsUser }}
      containers:
        - name: hyperion-supervisor
          image: {{ .Values.application.imageRepository}}/hyperion:{{ .Values.application.imageVersion }}
          command: ['/bin/bash', '-c']
          args:
            - |
              . /app/mx-bluesky/.venv/bin/activate
              hyperion --mode supervisor \
                --client-config /etc/hyperion/client_config.yaml \
                --supervisor-config /etc/hyperion/supervisor_config.yaml
              {{- if .Values.supervisor.enableDebugging }} \
                --debug-port {{ .Values.supervisor.debugPort }}
              {{- end }}
              {{- if .Values.application.dev }} \
                --dev
              sleep 600
              {{- end }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - name: rest-api
              containerPort: {{ .Values.supervisor.containerPort }}
              protocol: TCP
            {{- if .Values.supervisor.enableDebugging }}
            - name: debug
              containerPort: {{ .Values.supervisor.debugPort }}
            {{- end }}
          env:
            - name: LOG_DIR
              value: /var/log/bluesky
            - name: DEBUG_LOG_DIR
              value: /var/log/bluesky/debug
            - name: BEAMLINE
              value: "{{ .Values.application.beamline }}"
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.configServer.url }}"
            - name: PYTHONPATH
              value: "/scratch/mx-bluesky/src:/scratch/dodal/src"
            {{- range $key, $value := .Values.supervisor.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: "/status"
              port: {{ .Values.supervisor.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - mountPath: "/scratch"
              name: scratch
              readOnly: true
            - mountPath: "/etc/hyperion"
              name: supervisor-config
              readOnly: true
            - mountPath: "/var/log/bluesky"
              name: logdir
            - name: etc
              mountPath: /etc/passwd
              subPath: passwd
            - name: etc
              mountPath: /etc/group
              subPath: group
          securityContext:
            runAsGroup: {{ .Values.supervisor.runAsGroup }}
            runAsUser: {{ .Values.supervisor.runAsUser }}
        - name: hyperion-callbacks
          image: {{ .Values.application.imageRepository}}/hyperion:{{ .Values.application.imageVersion }}
          command: ['/bin/bash', '-c']
          args:
            - |
              . /app/mx-bluesky/.venv/bin/activate
              hyperion-callbacks \
                --watchdog-port {{ .Values.supervisor.containerPort }} \
                --stomp-config /etc/hyperion/blueapi_callbacks.yml
              {{- if .Values.callbacks.enableDebugging }} \
                --debug-port {{ .Values.callbacks.debugPort }}
              {{- end }}
              {{- if .Values.application.dev }} \
                --dev
              sleep 600
              {{- end }}
          securityContext:
            fsGroup: {{ .Values.callbacks.runAsGroup }}
            runAsGroup: {{ .Values.callbacks.runAsGroup }}
            runAsUser: {{ .Values.callbacks.runAsUser }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            {{- if .Values.supervisor.enableDebugging }}
            - name: debug
              containerPort: {{ .Values.supervisor.debugPort }}
            {{- end }}
          env:
            - name: LOG_DIR
              value: /var/log/bluesky
            - name: DEBUG_LOG_DIR
              value: /var/log/bluesky/debug
            - name: BEAMLINE
              value: "{{ .Values.application.beamline }}"
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.configServer.url }}"
            - name: PYTHONPATH
              value: "/scratch/mx-bluesky/src:/scratch/dodal/src"
            - name: ISPYB_CONFIG_PATH
              value: "/etc/secrets/expeye/ispyb.cfg"
          volumeMounts:
            - mountPath: "/scratch"
              name: scratch
              readOnly: true
            - mountPath: "/etc/hyperion"
              name: callbacks-config
              readOnly: true
            - mountPath: "/etc/zocalo"
              name: zocalo-config
              readOnly: true
            - mountPath: "/var/log/bluesky"
              name: logdir
            - mountPath: "/dls/{{ .Values.application.beamline }}/data"
              name: data
            - mountPath: "/etc/secrets/zocalo"
              name: zocalo-secrets
            - mountPath: "/etc/secrets/expeye"
              name: expeye-secrets
            - name: etc
              mountPath: /etc/passwd
              subPath: passwd
            - name: etc
              mountPath: /etc/group
              subPath: group
        - name: hyperion-scratch
          # container provided in order for vscode to attach to a writable scratch
          image: {{ .Values.application.imageRepository}}/hyperion:{{ .Values.application.imageVersion }}
          restartPolicy: Always
          volumeMounts:
            - mountPath: "/scratch"
              name: scratch
            - name: etc
              mountPath: /etc/passwd
              subPath: passwd
            - name: etc
              mountPath: /etc/group
              subPath: group
            - name: debug-home
              mountPath: /home/{{ .Values.supervisor.userName }}
          env:
            - name: HOME
              value: /home/{{ .Values.supervisor.userName }}
          command: ['/bin/bash', '-c']
          args:
            - |
              while true; do sleep 60; done
