apiVersion: v1
kind: Service
metadata:
  name: hyperion-supervisor-svc
spec:
  {{- if .Values.application.dev }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - name: hyperion-supervisor-rest
      port: {{ .Values.supervisor.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.supervisor.containerPort }}
  selector:
    app: hyperion-supervisor
