apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyperion-supervisor-scratch-{{ .Values.application.imageVersion }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.scratch.volumeSize }}
