apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperion-supervisor-deployment
spec:
  selector:
    matchLabels:
      app: hyperion-supervisor
  replicas: 1
  template:
    metadata:
      labels:
        app: hyperion-supervisor
    spec:
      volumes:
        # Bind some source folders for easier debugging
        - name: scratch
          persistentVolumeClaim:
            claimName: hyperion-supervisor-scratch-{{ .Values.application.imageVersion }}
        - name: config
          configMap:
            name: hyperion-supervisor-config
      initContainers:
        - name: hyperion-init
          image: {{ .Values.application.imageRepository}}/hyperion:{{ .Values.application.imageVersion }}
          command: ['/app/scripts/initialise_scratch.sh']
          volumeMounts:
            - name: scratch
              mountPath: "/scratch"
      containers:
        - name: hyperion-supervisor
          image: {{ .Values.application.imageRepository}}/hyperion:{{ .Values.application.imageVersion }}
          command: ['/scratch/mx-bluesky/utility_scripts/docker/entrypoint.sh']
          args:
            {{- if .Values.application.dev }}
            - "--dev"
            {{- end }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - name: rest-api
              containerPort: {{ .Values.application.containerPort }}
              protocol: TCP
          env:
            - name: LOG_DIR
              value: /var/log/bluesky
            - name: DEBUG_LOG_DIR
              value: /var/log/bluesky/debug
            - name: BEAMLINE
              value: "{{ .Values.application.beamline }}"
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.configServer.url }}"
          readinessProbe:
            exec:
              command: [ "/scratch/mx-bluesky/utility_scripts/docker/healthcheck.sh" ]
            periodSeconds: 5
          volumeMounts:
            - mountPath: "/scratch"
              name: scratch
              readOnly: true
            - mountPath: "/etc/hyperion"
              name: config
              readOnly: true
