env:
  sources:
    - kind: dodal
      module: dodal.beamlines.i24
    - kind: planFunctions
      module: mx_bluesky.beamlines.i24.serial
  events:
    broadcast_status_events: False
api:
  port: 25565
  cors:
    allow_credentials: True
    origins: 
      - "http://localhost:5173"
stomp:
  host: i24-control.diamond.ac.uk
