env:
  sources:
    - kind: dodal
      module: dodal.beamlines.i24
    - kind: planFunctions
      module: mx_bluesky.i24.serial
    - kind: planFunctions
      module: mx_bluesky.i24.serial.extruder
    - kind: planFunctions
      module: mx_bluesky.i24.serial.fixed_target
  events:
    broadcast_status_events: False
