
#Override this value on ixx-services values.yaml
beamline: dev

zocalo:
  defaultTransport: "PikaTransport"
  graylog:
    host: graylog-log-target.diamond.ac.uk
    port: 12208
    protocol: UDP
  secrets:
    - name: rabbitmq
      secretName: rmq-creds
      fileName: rabbitmq-credentials.yml
    - name: rabbitmq-api-reader
      secretName: rmq-api-reader
      fileName: rabbitmq-api-reader.yml

ispyb:
  secrets:
  - name: ispyb-creds
    secretName: ispyb-creds
    fileName: ispyb-credentials.yml

blueapi:

  image:
    repository: ghcr.io/diamondlightsource/mx-bluesky-blueapi

  hostNetwork: true

  extraEnvVars:
    - name: LOG_DIR
      value: /var/log/bluesky
    - name: DEBUG_LOG_DIR
      value: /var/log/bluesky-debug
    
    # This these ArgoCD
    # - name: BEAMLINE
    #   value: "{{ .Values.beamline }}"

    # - name: ZOCALO_GO_HOSTNAME
    # value: "{{ .Values.beamline }}-control"

    - name: ZOCALO_GO_USER
      value: "gda2"

    - name: ZOCALO_CONFIG
      value: "/zocalo/config/configuration.yaml"
    - name: ISPYB_CONFIG_PATH
      value: "/ispyb-config/config/configuration.yaml"

  worker:
    # This scratch part needs to go in ArgoCD
    # scratch:
    #   root: /dls_sw/ixx/software/bluesky/scratch
    #   repositories:
    #     - name: "dodal"
    #       remote_url: https://github.com/DiamondLightSource/dodal.git
    #     - name: "mx_bluesky"
    #       remote_url: https://github.com/DiamondLightSource/mx_bluesky.git
    logging:
      level: "INFO"
      graylog:
        enabled: False
        host: "graylog-log-target.diamond.ac.uk"
        port: 12231 #Dodal stream
   
  volumes:
  - name: zocalo-config
    configMap:
      name: "{{ .Release.Name }}-zocalo-config"
  - name: zocalo-secrets
    projected:
      defaultMode: 0444
      sources:
      - secret:
          name: rabbitmq # Should match secret name defined above
      - secret:
          name: rabbitmq-api-reader
  - name: ispyb-config
    configMap:
      name: ispyb-config"
  - name: ispyb-secrets
    sources:
    - secret:
      name: ispyb-creds
  - name: debuglogs
  - name: data
    hostPath:
      type: Directory
      path: "/dls/{{ .Values.beamline }}/data"

  # Put this one in argo
  # - name: dls-sw-bl
  #   hostPath:
  #     path: "/dls_sw/{{ .Values.beamline }}"
  #     type: Directory

  volumeMounts:
  - mountPath: "/dls_sw/{{ .Values.beamline }}"
    name: dls-sw-bl
    readOnly: true
    mountPropagation: HostToContainer


  # TODO figure out what to do about logs - if they aren't mounted, these paths should just be created in the container but 
  # be temporary. They should be sent to graylog too though
  
  # - mountPath: "/var/log/bluesky"
  #   name: logs
  # - mountPath: "/var/log/bluesky-debug"
  #   name: debuglogs

  # Put this in Argo
  # - mountPath: "/dls/{{ .Values.application.beamline }}/data"
  #   name: data
  - mountPath: "/zocalo/config"
    name: zocalo-config
  - mountPath: "/zocalo/secrets"
    name: zocalo-secrets

  # Configuration for the initContainer.
  # If enabled, the scratch section of the above configuration is mounted and
  # each repository is installed into a virtualEnv that the  main container uses.
  # These installations are editable, so code changes will be reflected when the
  # service performs an environment reload.
  initContainer:
    enabled: true
