name: System Tests
on:
  workflow_dispatch:
      inputs:
        python-version:
          description: Python version
          required: true
          default: "3.11"
          type: string
jobs:
  run-system-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - if: inputs.python-version != 'dev'
        name: Install latest versions of python packages
        uses: ./.github/actions/install_requirements
        with:
          python-version: ${{ inputs.python-version }}
          pip-install: ".[dev]"

      - name: Run tests
        run: tox -e system-tests
